version: '3'

services:
  warehouse_service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - db
    networks:
      - postgres

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5555:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
